webtalk_init -webtalk_dir D:/0_Personal_File/Grade2_01_Autumn/CO/P7/P7_L0_CPU/P7_L0_CPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 19 23:43:45 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "084bb51b-dbd8-42cc-a863-f352b6fe23ae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "002ca184d84b4e238c1c2a3099d50694" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9452_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2550045164 -regid "" -xml D:/0_Personal_File/Grade2_01_Autumn/CO/P7/P7_L0_CPU/P7_L0_CPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb2_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/0_Personal_File/Grade2_01_Autumn/CO/P7/P7_L0_CPU/P7_L0_CPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb2_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/0_Personal_File/Grade2_01_Autumn/CO/P7/P7_L0_CPU/P7_L0_CPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
